[package]
name = "order_book"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.0.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid7 = "1.0.1"
